# Generated by Django 3.2.4 on 2022-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flan_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia_uuid', models.UUIDField()),
                ('direccion', models.CharField(max_length=64)),
                ('telefono', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
