# Generated by Django 3.2.4 on 2022-04-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_sucursales_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursales',
            old_name='fotografia_uuid',
            new_name='sucursales_uuid',
        ),
    ]
