# Generated by Django 3.2.4 on 2022-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_fotografia_uuid_sucursales_sucursales_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursales',
            name='correo',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursales',
            name='horario',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
